<!-- for VIEWING ONLY -->
<?php
// ON CONCOURSE ? DISPLAY
// DISPLAY TOTAL AREA(sqft)
// DISPLAY TOTAL SPACES
// DISPLAY FEATURES EX(REFER TO REAL ESTATE WEBSITES)
// DISPLAY LOCATION(CITY/ ,POSTAL CODE BARANGAY)
// ADD A REVIEW/ FEEDBACK(COMMENT)OR STAR(TENANT CAN GIVE FEEDBACKS)
