<!-- for owners -->
<?php

// map configuration(ADDING SPACES/ BILLS) LINK?
// SETTING UP THE BUSINESS/CONCOURSE ADDING IMAGE(CHANGE THE UPLOADED MAP INTO IMAGE)


// ON CONCOURSE ? DISPLAY/ ADD
// DISPLAY TOTAL AREA(sqft)
// DISPLAY TOTAL SPACES
// DISPLAY FEATURES EX(REFER TO REAL ESTATE WEBSITES)
// DISPLAY LOCATION(CITY/ ,POSTAL CODE BARANGAY)
// ADD A REVIEW/ FEEDBACK(COMMENT)OR STAR(TENANT CAN GIVE FEEDBACKS)


// PER SPACES
// SPACE NO:
// DESCRIPTIONS: 1. floor-area(sqm or sqft) 2.windows 3.electricity(sockets) 4.(lights)
// SPACE NAME: ?? WILL CHANGE DEPENDS ON THE TENANT(PANGALAN NUNG SPACE/STORE)
